In [1]:
import numpy as np

In [13]:
#creating numpy arrays
l=(1,2,3)
np.array(l)
print(np.zeros(10))
a=np.ones(10,int)
a[0]="1"
a.dtype

#multidimesnsional
b=np.zeros((2,3,2))

[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]


In [23]:
b[0][1][0]
a[2:4]
print(b.shape)
a=np.array([[1,2,3],[4,5,6]])
a[0]
a[:,2:4]

(2, 3, 2)


array([[3],
       [6]])

In [28]:
#numpy operations
a=np.array([1,2,3])
b=np.array([4,5,6])
print(a+2)
print(a+b)
print(a*2)
print(a*b)
print(a**2)
print(a**b)

[3 4 5]
[5 7 9]
[2 4 6]
[ 4 10 18]
[1 4 9]
[  1  32 729]


In [35]:
print(a.mean())
print(a.sum())

2.0
6


In [43]:
import math as m
a=np.array([1,2,3])
b=np.array([4,5,6])
d=((a-b)**2).sum()
m.sqrt(d)

5.196152422706632

In [46]:
a1=np.array([[1,2],[3,4]])
a2=np.array([[10,20],[30,40]])
a1.dot(a2)


array([[ 70, 100],
       [150, 220]])

In [47]:
a=np.array([0,1,2,3])
b=np.array([2,3,4,5])
a.dot(b)

26